# Generated by Django 6.1.1 on 2026-09-09 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0004_team_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=200)),
                ('work_completed', models.TextField(blank=True)),
                ('problems', models.TextField(blank=True)),
                ('next_day_plan', models.TextField(blank=True)),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('mentor_remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='iic.team')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
