# Generated by Django 6.1.1 on 2026-09-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0005_dailyprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
