# Generated by Django 6.1.1 on 2026-09-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0006_externalmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to='iic.externalmember')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_members', to='iic.team')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('team', 'member'), name='unique_external_team_member')],
            },
        ),
    ]
