# Generated by Django 6.1.1 on 2026-09-10 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0008_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalVenture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venture_id', models.CharField(max_length=50, unique=True)),
                ('venture_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('membership_start', models.DateField(blank=True, null=True)),
                ('membership_end', models.DateField(blank=True, null=True)),
                ('space_allocated', models.CharField(blank=True, max_length=150)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('INACTIVE', 'Inactive')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['venture_name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('problem_statement', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('development_level', models.CharField(choices=[('IDEA', 'Idea'), ('THEORY', 'Theory'), ('PROTOTYPE', 'Prototype'), ('WORKING_PROTOTYPE', 'Working Prototype'), ('COMPLETED', 'Completed')], default='IDEA', max_length=30)),
                ('current_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='external_member',
        ),
        migrations.RemoveConstraint(
            model_name='externalteammember',
            name='unique_external_team_member',
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['register_number']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['team', 'student']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='attendance_marked',
        ),
        migrations.RemoveField(
            model_name='team',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='team',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_type',
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iicmembership',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iic_memberships', to='iic.student'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('LEADER', 'Team Leader'), ('MEMBER', 'Team Member')], default='MEMBER', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='eventregistration',
            constraint=models.UniqueConstraint(fields=('student', 'event'), name='unique_student_event_registration'),
        ),
        migrations.AddField(
            model_name='externalpayment',
            name='venture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='iic.externalventure'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='external_venture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='iic.externalventure'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='iic.team'),
        ),
        migrations.RemoveField(
            model_name='externalteammember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='externalteammember',
            name='team',
        ),
        migrations.DeleteModel(
            name='ExternalMember',
        ),
        migrations.DeleteModel(
            name='ExternalTeamMember',
        ),
    ]
