# Generated by Django 6.1.1 on 2026-09-10 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iic', '0009_externalpayment_externalventure_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organizing_college', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('HACKATHON', 'Hackathon'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('SEMINAR', 'Seminar'), ('CONFERENCE', 'Conference'), ('QUIZ', 'Quiz'), ('PAPER_PRESENTATION', 'Paper Presentation'), ('PROJECT_EXPO', 'Project Expo'), ('OTHER', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('venue', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PARTICIPATED', 'Participated'), ('WINNER', 'Winner'), ('FIRST', 'First Prize'), ('SECOND', 'Second Prize'), ('THIRD', 'Third Prize'), ('RUNNER_UP', 'Runner Up'), ('SPECIAL', 'Special Award')], max_length=30)),
                ('prize_name', models.CharField(blank=True, max_length=200)),
                ('prize_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='achievement_certificates/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='iic.externalevent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='iic.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
